"""
Concept Map Models
Stores user-generated concept maps with nodes, edges, and source attribution
"""

from sqlalchemy import Column, Integer, String, DateTime, Text, ForeignKey, Float
from datetime import datetime
from db import Base
from sqlalchemy.orm import relationship

class ConceptMap(Base):
    """
    Stores concept maps generated by users
    Each map contains nodes (concepts) and edges (relationships)
    """
    __tablename__ = "concept_maps"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)  # Links to User.id
    topic = Column(String, nullable=False)  # User-defined topic (e.g., "Machine Learning")
    
    # JSON storage for map structure
    map_data = Column(Text, nullable=True)  # Stores nodes and edges as JSON string
    sources = Column(Text, nullable=True)  # Stores document and web sources as JSON string
    
    # Metadata
    node_count = Column(Integer, default=0)  # Number of concept nodes
    edge_count = Column(Integer, default=0)  # Number of relationships
    source_document_count = Column(Integer, default=0)
    source_web_count = Column(Integer, default=0)

    # ✅ NEW: Store edges as JSON
    edges_json = Column(Text, nullable=True)
    # Confidence score
    confidence_score = Column(Float, default=0.0)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    user = relationship("User", backref="concept_maps")
    nodes = relationship("ConceptMapNode", back_populates="concept_map", cascade="all, delete-orphan")
    def __repr__(self):
        return f"<ConceptMap(id={self.id}, user_id={self.user_id}, topic='{self.topic}', nodes={self.node_count})>"


class ConceptMapNode(Base):
    """
    Optional: Stores individual concept nodes for advanced querying
    This is optional - you can store everything in map_data JSON instead
    """
    __tablename__ = "concept_map_nodes"
    
    id = Column(Integer, primary_key=True, index=True)
    map_id = Column(Integer, ForeignKey("concept_maps.id"), nullable=False)
    node_id = Column(String, nullable=False)  # Unique ID within the map
    label = Column(String, nullable=False)  # Concept name
    definition = Column(Text, nullable=True)  # Concept definition
    source_type = Column(String, nullable=True)  # "document", "web", or "both"
    sources_json = Column(Text, nullable=True)  # JSON array of specific sources
    # Relationship
    concept_map = relationship("ConceptMap", back_populates="nodes")
    def __repr__(self):
        return f"<ConceptMapNode(id={self.id}, label='{self.label}', source={self.source_type})>"
